# Configuration for training with pretrained weights
model:
  name: "unet_vae"
  input_channels: 3
  latent_dim: 512
  hidden_dims: [64, 128, 256, 512, 512]
  use_attention: true
  use_skip_connections: true
  
  # Pretrained encoder options
  pretrained_encoder: "resnet"  # Options: resnet, vggface, vae, stylegan, none
  encoder_checkpoint: null  # Path to checkpoint if using vae or stylegan
  freeze_encoder_stages: 2  # Number of encoder stages to freeze

# Modified training settings for transfer learning
training:
  # Start with lower learning rate for pretrained
  learning_rate: 0.0001
  
  # Different learning rates for encoder and decoder
  encoder_lr: 0.00001  # Lower LR for pretrained encoder
  decoder_lr: 0.0002   # Higher LR for decoder
  
  # Warm-up for pretrained models
  warmup_epochs: 5
  
  # Progressive unfreezing
  unfreeze_schedule:
    epoch_5: 3   # Unfreeze stage 3 at epoch 5
    epoch_10: 2  # Unfreeze stage 2 at epoch 10
    epoch_15: 1  # Unfreeze stage 1 at epoch 15
    epoch_20: 0  # Unfreeze all at epoch 20

# Two-stage training
two_stage:
  enabled: true
  stage1:
    epochs: 30
    task: "reconstruction"  # Train without masks first
    freeze_encoder: false
  stage2:
    epochs: 70
    task: "inpainting"  # Fine-tune with masks
    freeze_encoder: false